-- ============================================================
-- Migration: Ajout des 6 nouveaux templates d'emails Nathalie
-- ============================================================

INSERT INTO email_templates (id, name, subject, body, variables) VALUES
('convocation_v2', 'Convocation (nouvelle version)',
 'Convocation formation {{formation}} — {{dates}}',
 E'Bonjour,\n\nComment allez-vous ?\n\nComme convenu, je vous transmets un complément d''information relatif à la formation qui se tiendra :\n\nEn {{lieu}}\nDates : {{dates}}\n\nNous commencerons à 8h30 et nous terminerons à 17h00. Le repas de midi se déroulera au plus rapide, sur place.\n\nJe vous laisse le soin d''informer vos collaborateurs de la tenue de cette formation, et de ses objectifs pédagogiques.\n\nMerci de bien vouloir trouver ici un questionnaire amont à leur intention. Celui-ci a pour but de bien identifier leurs attentes et leur niveau. Il est très important que tous me le renvoient, avant le {{date_limite_questionnaire}}.\n\n{{lien_questionnaire}}\n\nJe vous remercie de veiller en particulier :\n- aux conditions de confort pour travailler en salle, dans vos locaux (chauffage, climatisation, table et chaises en nombre suffisant, bouteilles d''eau)\n- aux facilités d''accès pour les personnes handicapées. Merci de me prévenir si un des apprenants a un handicap (mobilité réduite, malentendant, malvoyant, "dys")\n- à la mise en place d''un paperboard ou tableau blanc\n- à la mise en place d''un vidéoprojecteur. Dans le cas où vous n''en auriez pas, veuillez me le signaler. J''amènerai le mien.\n\nIMPORTANT — J''ai créé pour vous un espace confidentiel où vous retrouverez tous les documents relatifs à la formation. En voici l''accès : {{url}} et votre mot de passe : {{password}}. Conservez-les précieusement.\n\nVous y trouverez :\n- la convention de formation. Merci de me la retourner signée.\n- la fiche pédagogique, telle que nous l''avons réfléchie ensemble\n- le livret d''accueil d''NJM Conseil (pour les apprenants)\n- la fiche de réclamation (pour les apprenants)\n\nJe vous rappelle qu''une évaluation des acquis aura lieu en cours ou en fin de formation.\n\nJe vous transmettrai, via votre espace, un bilan de formation, un exemplaire de l''attestation et du certificat de fin de formation.\n\nPlusieurs mois après la formation, je reviendrai vers vous pour évaluer les acquis dans le cadre professionnel.\n\nEn vous remerciant pour votre confiance.\n\nNathalie JOULIE MORAND\nNJM Conseil',
 '{{formation}}, {{dates}}, {{lieu}}, {{date_limite_questionnaire}}, {{lien_questionnaire}}, {{url}}, {{password}}'),

('fin_formation_v2', 'Mail fin de formation (nouvelle version)',
 'Suite formation {{formation}} — Documents et questionnaires',
 E'Bonjour,\n\nTout va bien pour vous ? J''espère que l''équipe est satisfaite de la formation.\n\nJe vous transmets ici plusieurs éléments relatifs à la démarche qualité de la formation. C''est important que ce soit complété par chaque personne qui a suivi la formation :\n- un questionnaire de satisfaction : {{lien_satisfaction}}\n- un questionnaire d''évaluation des acquis : {{lien_evaluation}}\n\nPar ailleurs, je vous transmets à nouveau le lien et le mot de passe de votre espace confidentiel NJM Conseil.\nLien : {{url}}\nMot de passe : {{password}}\n\nVous y trouverez tous les documents pour l''OPCO : feuilles de présence, certificats de fin de formation.\nVous pourrez aussi y récupérer :\n- pour vous : le bilan de la formation\n- pour les apprenants : le support pédagogique, les grilles d''évaluation\n\nAutre chose, ce serait sympa de prendre 1 minute pour déposer un avis sincère sur Google. Cela me donnera plus de visibilité sur le net. Merci d''aller sur : https://g.page/r/CTDsPUbHjCnREB0/review\n\nDésolée, cela fait de la paperasse mais c''est indispensable par rapport à la prise en charge de la formation.\n\nMerci encore à vous et à toute l''équipe pour la gentillesse de votre accueil.\n\nNathalie JOULIE MORAND\nNJM Conseil',
 '{{formation}}, {{lien_satisfaction}}, {{lien_evaluation}}, {{url}}, {{password}}'),

('relance_convention_v2', 'Relance convention signée',
 'Relance convention signée — {{formation}}',
 E'Bonjour,\n\nVous allez bien ?\n\nJe me permets de revenir vers vous au sujet de la formation à venir.\n\nSauf erreur de ma part, je n''ai pas reçu la convention signée. Pouvez-vous me la transmettre au plus tôt ?\n\nDésolée pour ce côté administratif mais la démarche qualité Qualiopi exige ce document signé des deux parties.\n\nEn vous remerciant par avance.\n\nNathalie JOULIE MORAND\nNJM Conseil',
 '{{formation}}, {{dirigeant}}'),

('relance_questionnaires', 'Relance questionnaires fin formation',
 'Relance questionnaires — {{formation}}',
 E'Bonjour,\n\nJ''espère que vous allez bien.\n\nA l''issue de la formation, je vous ai transmis un mail avec 2 questionnaires à compléter par chaque apprenant. Ces derniers sont importants pour mesurer l''impact de la formation et pour répondre aux exigences de la démarche qualité Qualiopi.\n\nSauf erreur de ma part, les questionnaires n''ont pas été complétés à ce jour. Pouvez-vous les transmettre à nouveau aux apprenants et leur demander de les remplir au plus tôt ?\n\nQuestionnaire d''évaluation des acquis : {{lien_evaluation}}\nQuestionnaire de satisfaction : {{lien_satisfaction}}\n\nEn vous remerciant par avance.\n\nNathalie JOULIE MORAND\nNJM Conseil',
 '{{formation}}, {{lien_satisfaction}}, {{lien_evaluation}}'),

('avis_google_sous_traitant', 'Demande avis Google (avec sous-traitant)',
 'Formation {{formation}} — Votre avis nous intéresse',
 E'Bonjour à tous,\n\nMerci pour votre participation active à la formation menée par {{formateur}}.\n\nIl m''a fait un retour de votre travail et de vos avancées.\n\nSi vous souhaitez que la formation soit efficace, il est important que vous mettiez en pratique au quotidien les outils et méthodes vus et que vous travailliez tout particulièrement vos axes d''amélioration très régulièrement.\n\nOn compte sur vous !\n\nA l''attention de votre manager et de vous-mêmes : nous vous serions reconnaissants de compléter un avis Google sincère. Cela prend 2 minutes et cela améliore notre visibilité digitale. Le lien : https://g.page/r/CTDsPUbHjCnREB0/review\n\nMerci beaucoup par avance.\n\nLa formation commence maintenant, à vous de jouer !\n\nBien cordialement\n\nNathalie JOULIE MORAND\nNJM Conseil',
 '{{formation}}, {{formateur}}'),

('avis_google_direct', 'Demande avis Google (sans sous-traitant)',
 'Formation {{formation}} — Votre avis nous intéresse',
 E'Bonjour à tous,\n\nMerci pour votre participation active à la formation sur laquelle je vous ai accompagnés.\n\nSi vous souhaitez que la formation soit efficace, il est important que vous mettiez en pratique au quotidien les outils et méthodes vus et que vous travailliez tout particulièrement vos axes d''amélioration très régulièrement.\n\nJe compte sur vous !\n\nA l''attention de votre manager et de vous-mêmes : je vous serai reconnaissante de compléter un avis Google sincère. Cela prend 2 minutes et cela améliore la visibilité digitale d''NJM Conseil. Le lien : https://g.page/r/CTDsPUbHjCnREB0/review\n\nMerci beaucoup par avance.\n\nLa formation commence maintenant, à vous de jouer !\n\nBien cordialement\n\nNathalie JOULIE MORAND\nNJM Conseil',
 '{{formation}}')
ON CONFLICT (id) DO UPDATE SET subject = EXCLUDED.subject, body = EXCLUDED.body, variables = EXCLUDED.variables, updated_at = NOW();
